project_name: k8stunnel
env:
- CGO_ENABLED=0
- GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- binary: k8stunnel
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
